export const employeeConstants = {
    GETALL_REQUEST: 'GETALL_REQUEST',
    GETALL_SUCCESS: 'GETALL_SUCCESS',
    GETALL_FAILURE: 'GETALL_FAILURE',

    EDIT_SUCCESS: 'EDIT_SUCCESS',
    EDIT_FAILURE: 'EDIT_FAILURE'
};